bboard/urls.py
from django.urls import path
from django.views.generic import CreateView

from bboard.models import Bb
from bboard.views import (index, by_rubric, BbCreateView,
                          add, add_and_save,
                          BbRubricBbsView, BbDetailView, BbEditView, BbDeleteView)

app_name = 'bboard'

urlpatterns = [
    path('add/', BbCreateView.as_view(), name='add'),
    # path('add/', CreateView.as_view(model=Bb,
    #                                   template_name='create.html')),
    # path('add/', add_and_save, name='add'),

    # path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('<int:rubric_id>/', BbRubricBbsView.as_view(), name='by_rubric'),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),

    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('', index, name='index'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('testapp/', include('testapp.urls')),

    path('', include('bboard.urls', namespace='bboard')),
]

bboard/models.py
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models


def get_min_length():
    min_length = 4
    # Вычисления
    return

def validate_even(val):
    if val % 2 != 0:
        raise ValidationError('Число %(value)s нечётное',
                              code='odd',
                              params={'value': val})


class MinMaxValueValidator:
    def __init__(self, min_value, max_value):
        self.min_value = min_value
        self.max_value = max_value

    def __call__(self, val):
        if val < self.min_value or val > self.max_value:
            raise ValidationError(
                'Введённое число должно находиться в диапазоне'
                'от %(min)s до %(max)s',
                code='out_of_range',
                params={'min': self.min_value, 'max': self.max_value},
            )



class Rubric(models.Model):
    name = models.CharField(
        max_length=20,
        db_index=True,
        verbose_name='Название',
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'
        ordering = ('name',)


class Bb(models.Model):
    # KINDS = (
    #     ('b', 'Куплю'),
    #     ('s', 'Продам'),
    #     ('c', 'Обменяю'),
    # )

    KINDS = (
        ('Купля-продажа', (
            ('b', 'Куплю'),
            ('s', 'Продам'),
        )),
        ('Обмен', (
            ('c', 'Обменяю'),
        ))
    )

    # KINDS = (
    #     (None, 'Выберите тип публикуемого объявления'),
    #     ('b', 'Куплю'),
    #     ('s', 'Продам'),
    #     ('c', 'Обменяю'),
    # )

    kind = models.CharField(
        max_length=1,
        choices=KINDS,
        default='s',
        verbose_name='Тип объявления',
    )

    title = models.CharField(
        max_length=50,
        verbose_name='Товар',
        validators=[
            validators.RegexValidator(regex=r'^.{4,}$',),
            # validators.MinLengthValidator(get_min_length),
        ],
        error_messages={'invalid': 'Введите 4 или более символов'}
    )

    content = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание',
    )

    price = models.DecimalField(
        max_digits=13,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name='Цена',
        validators=[validate_even],
    )

    published = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Опубликовано',
    )

    rubric = models.ForeignKey(
        # Rubric,
        'Rubric',
        # 'bboard.Rubric',
        null=True,
        on_delete=models.PROTECT,
        verbose_name='Рубрика',
    )

    def __str__(self):
        return f'Объявление: {self.title}'

    # def save(self, *args, **kwargs):
    #     if self.is_model_correct():
    #         super().save(*args, **kwargs)
    #
    # def delete(self, *args, **kwargs):
    #     if self.need_to_delete():
    #         super().delete(*args, **kwargs)

    # Функциональное поле
    def title_and_price(self):
        if self.price:
            return f'{self.title} ({self.price})'
        return f'{self.title}'

    title_and_price.short_description = 'Название и цена'

    def clean(self):
        errors = {}
        if not self.content:
            errors['content'] = ValidationError(
                'Укажите описание продаваемого товара'
            )

        if self.price and self.price < 0:
            errors['price'] = ValidationError(
                'Укажите неотрицательное значение цены'
            )

        if errors:
            raise ValidationError(errors)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-published']

bboard/forms.py
from django.forms import ModelForm

from bboard.models import Bb, Rubric


class BbForm(ModelForm):
    class Meta:
        model = Bb
        fields = ('title', 'content', 'price', 'rubric')

bboard/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.decorators.http import require_GET, require_POST, require_safe, require_http_methods
from django.views.generic import CreateView, FormView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView

from bboard.forms import BbForm
from bboard.models import Bb, Rubric


def index(request):
    bbs = Bb.objects.all()
    rubrics = Rubric.objects.all()
    context = {'bbs': bbs, 'rubrics': rubrics}

    return render(request, 'index.html', context)


def by_rubric(request, rubric_id):
    bbs = Bb.objects.filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    current_rubric = Rubric.objects.get(pk=rubric_id)
    context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}
    return render(request, 'by_rubric.html', context)


# class BbCreateView(CreateView):
#     template_name = 'create.html'
#     form_class = BbForm
#     success_url = reverse_lazy('index')
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['rubrics'] = Rubric.objects.all()
#         return context


# class BbCreateView(CreateView):
#     template_name = 'create.html'
#     model = Bb
#     form_class = BbForm



# class BbCreateView(View):
#     def get(self, request, *args, **kwargs):
#         form = BbForm()
#         context = {'form': form, 'rubrics': Rubric.objects.all()}
#         return render(request, 'create.html', context)
#
#     def post(self, request, *args, **kwargs):
#         form = BbForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('bboard:index'))
#         else:
#             context = {'form': form, 'rubrics': Rubric.objects.all()}
#             return render(request, 'create.html', context)


# class BbCreateView(FormView):
class BbCreateView(CreateView):
    template_name = 'bboard/bb_create.html'
    form_class = BbForm
    initial = {'price': 0.0}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context

    def get_success_url(self):
        return reverse('bboard:by_rubric',
                       kwargs={'rubric_id': self.object.cleaned_data['rubric'].pk})


class BbEditView(UpdateView):
    model = Bb
    form_class = BbForm
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


class BbDeleteView(DeleteView):
    model = Bb
    success_url = '/{rubric_id}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


# class BbRubricBbsView(TemplateView):
#     template_name = 'by_rubric.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['bbs'] = Bb.objects.filter(rubric=context['rubric_id'])
#         context['rubrics'] = Rubric.objects.all()
#         context['current_rubric'] = Rubric.objects.get(pk=context['rubric_id'])
#         return context


class BbRubricBbsView(ListView):
    # template_name = 'by_rubric.html'
    context_object_name = 'bbs'

    def get_queryset(self):
        return Bb.objects.filter(rubric=self.kwargs['rubric_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        context['current_rubric'] = Rubric.objects.get(pk=self.kwargs['rubric_id'])
        return context


class BbDetailView(DetailView):
    model = Bb
    # template_name = 'bb_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context


def add(request):
    bbf = BbForm()
    context = {'form': bbf}
    return render(request, 'add.html', context)


# @require_GET
# @require_POST
# @require_safe
@require_http_methods(['GET', 'POST'])
def add_and_save(request):
    rubrics = get_list_or_404(Rubric)

    if request.method == 'POST':
        bbf = BbForm(request.POST)
        if bbf.is_valid():
            bbf.save()
            return HttpResponseRedirect(
                reverse('bboard:by_rubric',
                        kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk}))
        else:
            context = {'form': bbf, 'rubrics': rubrics}
            return render(request, 'add.html', context)
    else:
        bbf = BbForm()
        context = {'form': bbf, 'rubrics': rubrics}
        return render(request, 'add.html', context)


def bb_detail(request, bb_id):
    bb = get_object_or_404(Bb, pk=bb_id)
    context = {'bb': bb}
    return render(request, 'bb_detail.html', context)

templates/bboard/bb_confirm_delete.html
{% extends 'layout/basic.html' %}

{% block title %}Удалить объявление{% endblock %}

{% block content %}
    <h2>Удалить объявление</h2>
    <p>Рубрика: {{ bb.rubric.name }}</p>
    <p>Товар: {{ bb.title }}</p>
    <p>{{ bb.content }}</p>
    <p>Цена: {{ bb.price }} тг.</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Удалить</button>
    </form>
{% endblock %}

templates/bboard/bb_create.html
{% extends 'layout/basic.html' %}

{% block title %}Добавление объявления{% endblock %}

{% block content %}

    <h1>Добавление объявления</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {# <input type="submit" value="Добавить"> #}
        <button type="submit">Добавить</button>
    </form>

{% endblock %}

templates/bboard/bb_detail.html
{% extends 'layout/basic.html' %}

{% block title %}{{ bb.title }}{% endblock %}

{% block content %}
    <p>Рубрика: {{ bb.rubric.name }}</p>
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p>Цена: {{ bb.price|floatformat:'2g' }} тг.</p>

    <p>
        <a href="{% url 'bboard:edit' bb.pk %}">
            <button type="button">Изменить</button></a>

        <a href="{% url 'bboard:delete' bb.pk %}">
            <button type="button">Удалить</button></a>
    </p>

{% endblock %}

templates/bboard/bb_form.html
{% extends 'layout/basic.html' %}

{% block title %}Изменение объявления{% endblock %}

{% block content %}

    <h1>Изменение объявления</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Изменить</button>
    </form>

{% endblock %}

templates/bboard/bb_list.html
{% extends 'layout/basic.html' %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}

    <h2>Рубрика: {{ current_rubric.name }}</h2>

    {% for bb in bbs %}
        <div>
            <h2>
                {{ forloop.counter }}.
                <a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a>
            </h2>
            <p>{{ bb.content }}</p>
            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        </div>
    {% endfor %}

{% endblock %}

templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    <div>
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/bboard/create.html
{% extends "layout/basic.html" %}


{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

templates/bboard/index.html
{% extends "layout/basic.html" %}

{% block content %}
    {% for bb in bbs %}
    <div>
{#        <h2>{{ bb.title }}</h2>#}
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title_and_price }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
            {{ bb.rubric.name }}</a></p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

templates/bboard/rubric_bbs.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    <div>
        <h2>
            <a href="{% url 'bboard:detail' bb.pk %}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}