bboard/urls.py
from django.urls import path
from django.views.generic import CreateView

from bboard.models import Bb
from bboard.views import (index, by_rubric, BbCreateView,
                          add, add_and_save,
                          BbRubricBbsView, BbDetailView, BbEditView, BbDeleteView)

app_name = 'bboard'

urlpatterns = [
    path('add/', BbCreateView.as_view(), name='add'),
    # path('add/', CreateView.as_view(model=Bb,
    #                                   template_name='create.html')),
    # path('add/', add_and_save, name='add'),

    # path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('<int:rubric_id>/', BbRubricBbsView.as_view(), name='by_rubric'),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),

    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('', index, name='index'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('testapp/', include('testapp.urls')),

    path('', include('bboard.urls', namespace='bboard')),
]

templates/layout/basic.html
<!DOCTYPE html>

{% load static %}

<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}Главная{% endblock %} :: Доска объявлений</title>

    <link rel="stylesheet" href="{% static 'bboard/style.css' %}" />
  </head>
  <body>
    <header>
      <h1>Объявления</h1>
    </header>

    <nav>
      <a href="{% url 'bboard:index' %}">Главная</a>
      <a href="{% url 'bboard:add' %}">Добавить</a>

      {% for rubric in rubrics %}
          {% url 'bboard:by_rubric' rubric_id=rubric.pk as runric_url %}

      <a href="{{ runric_url }}"> 
        {{ rubric.name }} </a>

      {% endfor %}
    </nav>

    <section>{% block content %} {% endblock %}</section>
  </body>
</html>